# EuRoC stereo model

# intrinsic parameters after stereo-rectification are written
Camera:
  name: "D435i stereo"
  setup: "stereo"
  model: "perspective"

  # new "rectified" matrices is the first three cols of the projection matrix which is calculated with cv::stereoRectify()
  # e.g. fx = P1[0][0] or P2[0][0], cx = P1[0][2] or P2[0][2]
  #      fy = P1[1][1] or P2[1][1], cy = P1[1][2] or P2[1][2]

  fx: 377.229220831
  fy: 377.486565843
  cx: 326.351864976
  cy: 239.659665361

  # there is no distortion after stereo rectification

  k1: 0.0
  k2: 0.0
  p1: 0.0
  p2: 0.0
  k3: 0.0

  # focal_x_baseline is -P2[0][3] which is calculated with cv::stereoRectify()

  fps: 30.0
  cols: 640
  rows: 480
  focal_x_baseline: 0.094923 # in m
  depth_threshold: 40

  color_order: "Gray"

# original intrinsic parameters (K, D) and stereo-recitification parameters (R)
# matrices (K, R) are written in row-major order

StereoRectifier:
  K_left: 
    [
      377.229220831, 0.0, 326.351864976, 
      0.0, 377.486565843, 239.659665361, 
      0.0, 0.0, 1.0
    ]
  D_left: [0.0, 0.0, 0.0, 0.0, 0.0]
  R_left:
    [
      1.0, 0.0, 0.0,
      0.0, 1.0, 0.0,
      0.0, 0.0, 1.0,
    ]
  K_right: 
    [
      377.229220831, 0.0, 326.351864976, 
      0.0, 377.486565843, 239.659665361, 
      0.0, 0.0, 1.0
    ]
  D_right: [0.0, 0.0, 0.0, 0.0, 0.0]
  R_right:
    [
      1.0, 0.0, 0.0,
      0.0, 1.0, 0.0,
      0.0, 0.0, 1.0,
    ]

Preprocessing:
  min_size: 800

Feature:
  name: "default ORB feature extraction setting"
  scale_factor: 1.2
  num_levels: 8
  ini_fast_threshold: 20
  min_fast_threshold: 7

Mapping:
  backend: "g2o"
  baseline_dist_thr: 0.11007784219
  redundant_obs_ratio_thr: 0.9
  erase_temporal_keyframes: false
  num_temporal_keyframes: 15

Tracking:
  backend: "g2o"
  enable_temporal_keyframe_only_tracking: false
  margin_last_frame_projection: 10.0

KeyframeInserter:
  wait_for_local_bundle_adjustment: false

Relocalizer:
  search_neighbor: true

LoopDetector:
  backend: "g2o"

Initializer:
  min_num_triangulated_pts: 100

System:
  map_format: "msgpack"
  num_grid_cols: 47
  num_grid_rows: 30

PangolinViewer:
  keyframe_size: 0.07
  keyframe_line_width: 1
  graph_line_width: 1
  point_size: 2
  camera_size: 0.08
  camera_line_width: 3
  viewpoint_x: 0
  viewpoint_y: -0.65
  viewpoint_z: -1.9
  viewpoint_f: 400