stella_vslam:
  ros__parameters:
    map_frame: map_vslam
    odom_frame: odom_frame
    robot_base_frame: base_link
    camera_frame: camera
    publish_tf: true
    publish_keyframes: true
    use_exact_time: true # exact time SynchPolicy
