stella_vslam:
  ros__parameters:
    map_frame: map
    odom_frame: odom
    robot_base_frame: camera_link
    camera_frame: camera_link
    publish_tf: true
    publish_keyframes: true
    use_exact_time: true # exact time SynchPolicy